### ISSUE TITLE
Error : self signed certificate

### ISSUE THREAD

**Issue by joffrey71** [getwud/wud#227]
Hello,

I have a "self signed certificate" error when WUD is trying to process my docker container.

Here's my docker-compose file :

```
version: '3'
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    environment:
      TZ: 'France/Paris'
      WUD_LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3000
```

and here's my log : 
```10:00:00.836  WARN whats-up-docker/watcher.docker.local: Error when processing (Error: self signed certificate) (container=local_postgres_container)
10:00:00.837 DEBUG whats-up-docker/watcher.docker.local: Error: self signed certificate (container=local_postgres_container)
    RequestError: Error: self signed certificate
        at new RequestError (/home/node/app/node_modules/request-promise-core/lib/errors.js:14:15)
        at Request.plumbing.callback (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
        at Request.RP$callback [as _callback] (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
        at self.callback (/home/node/app/node_modules/request/request.js:185:22)
        at Request.emit (node:events:513:28)
        at Request.emit (node:domain:489:12)
        at Request.onRequestError (/home/node/app/node_modules/request/request.js:877:8)
        at ClientRequest.emit (node:events:513:28)
        at ClientRequest.emit (node:domain:489:12)
        at TLSSocket.socketErrorListener (node:_http_client:494:9)
        at TLSSocket.emit (node:events:513:28)
        at TLSSocket.emit (node:domain:489:12)
        at emitErrorNT (node:internal/streams/destroy:157:8)
        at emitErrorCloseNT (node:internal/streams/destroy:122:3)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
10:00:00.838  WARN whats-up-docker/watcher.docker.local: Error when processing (Error: self signed certificate) (container=local_frigate)
10:00:00.838 DEBUG whats-up-docker/watcher.docker.local: Error: self signed certificate (container=local_frigate)
    RequestError: Error: self signed certificate
        at new RequestError (/home/node/app/node_modules/request-promise-core/lib/errors.js:14:15)
        at Request.plumbing.callback (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
        at Request.RP$callback [as _callback] (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
        at self.callback (/home/node/app/node_modules/request/request.js:185:22)
        at Request.emit (node:events:513:28)
        at Request.emit (node:domain:489:12)
        at Request.onRequestError (/home/node/app/node_modules/request/request.js:877:8)
        at ClientRequest.emit (node:events:513:28)
        at ClientRequest.emit (node:domain:489:12)
        at TLSSocket.socketErrorListener (node:_http_client:494:9)
        at TLSSocket.emit (node:events:513:28)
        at TLSSocket.emit (node:domain:489:12)
        at emitErrorNT (node:internal/streams/destroy:157:8)
        at emitErrorCloseNT (node:internal/streams/destroy:122:3)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
10:00:00.840  WARN whats-up-docker/watcher.docker.local: Error when processing (Error: self signed certificate) (container=local_portainer)
10:00:00.840 DEBUG whats-up-docker/watcher.docker.local: Error: self signed certificate (container=local_portainer)
    RequestError: Error: self signed certificate
        at new RequestError (/home/node/app/node_modules/request-promise-core/lib/errors.js:14:15)
        at Request.plumbing.callback (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
        at Request.RP$callback [as _callback] (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
        at self.callback (/home/node/app/node_modules/request/request.js:185:22)
        at Request.emit (node:events:513:28)
        at Request.emit (node:domain:489:12)
        at Request.onRequestError (/home/node/app/node_modules/request/request.js:877:8)
        at ClientRequest.emit (node:events:513:28)
        at ClientRequest.emit (node:domain:489:12)
        at TLSSocket.socketErrorListener (node:_http_client:494:9)
        at TLSSocket.emit (node:events:513:28)
        at TLSSocket.emit (node:domain:489:12)
        at emitErrorNT (node:internal/streams/destroy:157:8)
        at emitErrorCloseNT (node:internal/streams/destroy:122:3)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
10:00:00.871  WARN whats-up-docker/watcher.docker.local: Error when processing (Error: self signed certificate) (container=local_homepage)
10:00:00.871 DEBUG whats-up-docker/watcher.docker.local: Error: self signed certificate (container=local_homepage)
    RequestError: Error: self signed certificate
        at new RequestError (/home/node/app/node_modules/request-promise-core/lib/errors.js:14:15)
        at Request.plumbing.callback (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
        at Request.RP$callback [as _callback] (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
        at self.callback (/home/node/app/node_modules/request/request.js:185:22)
        at Request.emit (node:events:513:28)
        at Request.emit (node:domain:489:12)
        at Request.onRequestError (/home/node/app/node_modules/request/request.js:877:8)
        at ClientRequest.emit (node:events:513:28)
        at ClientRequest.emit (node:domain:489:12)
        at TLSSocket.socketErrorListener (node:_http_client:494:9)
        at TLSSocket.emit (node:events:513:28)
        at TLSSocket.emit (node:domain:489:12)
        at emitErrorNT (node:internal/streams/destroy:157:8)
        at emitErrorCloseNT (node:internal/streams/destroy:122:3)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Does my configuration's wrong ?

Thanks :)

**Comment by fmartinou** [comment]
Hi,

What registry come these images from?
From the Docker Hub?
No self-hosted docker registry/docker registry proxy?

Or maybe are you using an outgoing proxy that would break the TLS tunnel (like Squid...)?

**Comment by glebaccon-eurekam** [comment]
Hello,

I'm digging up this subject because I have a similar problem. I use a custom registry in HTTPS with self CA certificate and I have this error:
`WARN whats-up-docker/watcher.docker.local: Error when processing (Error: unable to verify the first certificate) `

Do you have any suggestions to fix it?

**Comment by fmartinou** [comment]
Hi @joffrey71,

Node.js strictly verifies TLS certificates against public Certificate Authorities by default and rejects self-signed certificates for security.

To allow WUD to trust your self-signed or internal CA certificate:
1. Mount your CA certificate into the WUD container (e.g. `/certs/ca.crt`).
2. Set the environment variable:
   ```yaml
   environment:
     - NODE_EXTRA_CA_CERTS=/certs/ca.crt
   ```

Closing as this is standard Node.js security behavior.
