### ISSUE TITLE
WUD container is crashing

### ISSUE THREAD

**Issue by attilabalazsy** [getwud/wud#275]
I'm having issues with WUD as it continuesly crashing after couple of days/hours. The crash is mostly related to some communication or parsing issues, so most probably because of an incorrect error handling. 

WUD is monitoring 3 docker instances, one is running locally and 2 are accessed through TCP.
WUD is running on RPI4 (ARMv8)

This is the stack trace from the last crash:
23:00:00.742  INFO whats-up-docker/watcher.docker.rpi4: Cron started (0 * * * *)
23:00:13.565  INFO whats-up-docker/watcher.docker.rpi2: Cron finished (6 containers watched, 0 errors, 1 available updates)
23:00:15.464  INFO whats-up-docker/watcher.docker.rpi4: Cron finished (12 containers watched, 0 errors, 3 available updates)
23:00:15.633  WARN whats-up-docker/watcher.docker.docker02: Error when processing (502 - "<html><body><h1>502 Bad Gateway</h1>\nThe server returned an invalid or incomplete response.\n</body></html>\n\n") (container=docker02_Container-health-check)
23:00:15.637  WARN whats-up-docker/watcher.docker.docker02: Error when processing some containers (Cannot read properties of undefined (reading 'tag'))
23:00:15.637  INFO whats-up-docker/watcher.docker.docker02: Cron finished (0 containers watched, 0 errors, 0 available updates)
23:15:53.534  INFO whats-up-docker/watcher.docker.docker02: Status changed from running to exited (container=docker02_ntfy)
23:15:57.605  INFO whats-up-docker/watcher.docker.docker02: Status changed from running to exited (container=docker02_uptime-kuma)
23:15:57.790  INFO whats-up-docker/watcher.docker.docker02: Status changed from running to exited (container=docker02_apprise)
undefined:1
{"status":"create","id":"1a334ca38afd163d150f843df9c3c8ad218613b55e153ea74deb579dc5d49c16","from":"linuxserver/apprise-api","Type":"container","Action":"create","Actor":{"ID":"1a334ca38afd163d150f843df9c3c8ad218613b55e153ea74deb579dc5d49c16","Attributes":{"build_version":"Linuxserver.io version:- v0.9.0-ls67 Build-date:- 2023-04-03T05:02:18-05:00","com.docker.compose.config-hash":"30bccceeb345cb4d152861613bb376068abd38e7d626354329dc30280ffa507d","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:48cac8ed2b836ba0c44d96d1d8e6ac86c7d12b285495e70d4ac8fee4237d6964","com.docker.compose.oneoff":"False","com.docker.compose.project":"tools","com.docker.compose.project.config_files":"/data/compose/48/docker-compose.yml","com.docker.compose.project.working_dir":"/data/compose/48","com.docker.compose.service":"apprise","com.docker.compose.version":"2.13.0","image":"linuxserver/apprise-api","maintainer":"Roxedus","name":"apprise","org.opencontainers.image.authors":"linuxserver.io","org.opencontainers.image.created":"2023-04-03T05:02:18-05:00","org.opencontainers.image.description":"[Apprise-api](https://github.com/caronc/apprise-api) Takes advantage of [Apprise](https://github.com/caronc/apprise) through your network with a user-friendly API.    * Send notifications to more then 65+ services.  * An incredibly lightweight gateway to Apprise.  * A production ready micro-service at your disposal.    Apprise API was designed to easily fit into existing (and new) eco-systems that are looking for a simple notification solution.  ","org.opencontainers.image.documentation":"https://docs.linuxserver.io/images/docker-apprise-api","org.opencontainers.image.licenses":"GPL-3.0-only","org.opencontainers.image.ref.name":"9b00490ab0f3e7373807c8e0e6e3c71e4eb66d56","org.opencontainers.image.revision":"9b00490ab0f3e7373807c8e0e6e3c71e4eb66d56","org.opencontainers.image.source":"https://github.com/linuxserver/docker-apprise-api","org.opencontainers.image.title":"Apprise-api","org.opencontainers.image.url":"https://github.com/linuxserver/docker-apprise-api/packages","org.opencontainers.image.vendor":"linuxserver.io","org.opencontainers.image.version":"v0.9.0-ls67","traefik.docker.network":"proxy","traefik.enable":"true","traefik.http.middlewares.notify-https-redirect.redirectscheme.scheme":"https","traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto":"https","traefik.http.routers.notify-secure.entrypoints":"https","traefik.http.routers.notify-secure.middlewares":"cloudflare-real-ip@file, authelia@file","traefik.http.routers.notify-secure.rule":"Host(`*****.cloud`)","traefik.http.routers.notify-secure.tls":"true","traefik.http.routers.notify.entrypoints":"http","traefik.http.routers.notify.middlewares":"notify-https-redirect","traefik.http.routers.notify.rule":"Host(`notify.
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Docker.onDockerEvent (/home/node/app/watchers/providers/docker/Docker.js:324:34)
    at IncomingMessage.<anonymous> (/home/node/app/watchers/providers/docker/Docker.js:313:51)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:140:24)
    at HTTPParser.execute (<anonymous>)
    at Socket.socketOnData (node:_http_client:534:22)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by mcarlosro** [comment]
I also have the same error. Restarting WUD solve the problem but not sure why this is happening. I have WUD working all day but on a NAS restart (every morning) WUD crashes.

**Comment by xsolinsx** [comment]
I believe this is the same error, also happening usually after a restart
```
12:30:16.573  INFO whats-up-docker/watcher.docker.homeserver: Cron finished (42 containers watched, 0 errors, 0 available updates)
23:00:05.792 DEBUG whats-up-docker/watcher.docker.homeserver: Unable to get container details for container id=[220d35cc7819d56e37eb716032333d305ef55609aa0d78a34302536ee071c9d1]
23:00:05.794 DEBUG whats-up-docker/watcher.docker.homeserver: Unable to get container details for container id=[7a3f8b5e0f3ad4356f1e331a95f4820f328fd1465351da83499060dae2ae7473]
23:00:05.794 DEBUG whats-up-docker/watcher.docker.homeserver: Unable to get container details for container id=[220d35cc7819d56e37eb716032333d305ef55609aa0d78a34302536ee071c9d1]
23:00:05.814 DEBUG whats-up-docker/watcher.docker.homeserver: Unable to get container details for container id=[7a3f8b5e0f3ad4356f1e331a95f4820f328fd1465351da83499060dae2ae7473]
23:00:06.001 DEBUG whats-up-docker/watcher.docker.homeserver: Unable to get container details for container id=[a65d7e70c9f3580a2515953e0223788b2fb988c2b11b502b460539b8f178fe11]
undefined:1
{"status":"die","id":"a65d7e70c9f3580a2515953e0223788b2fb988c2b11b502b460539b8f178fe11","from":"acouvreur/sablier:1.8.0","Type":"container","Action":"die","Actor":{"ID":"a65d7e70c9f3580a2515953e0223788b2fb988c2b11b502b460539b8f178fe11","Attributes":{"com.docker.compose.config-hash":"28174730de00db17b32164e07be6af8460f9f9314dbc20dee3ca9bef8c94af9f","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:bbbe410eafe6efa0477275c31555ca44a6b43060df64cae3fdda80799c2af6d9","com.docker.compose.oneoff":"False","com.docker.compose.project":"homeserver","com.docker.compose.project.config_files":"/home/user/projects/docker-compose.yml","com.docker.compose.project.environment_file":"/etc/profile.d/projects_env_vars.sh","com.docker.compose.project.working_dir":"/home/user/projects","com.docker.compose.service":"sablier","com.docker.compose.version":"2.29.7","execDuration":"85784","exitCode":"0","image":"acouvreur/sablier:1.8.0","name":"sablier","org.opencontainers.image.created":"2024-10-02T00:45:19.507Z","org.opencontainers.image.description":"Start your containers on demand, shut them down automatically when there's no activity. Docker, Docker Swarm Mode and Kubernetes compatible.","org.opencontainers.image.licenses":"AGPL-3.0","org.opencontainers.image.revision":"2a2079c541f2c19cb062caaf8142339e11930231","org.opencontainers.image.source":"https://github.com/acouvreur/sabli

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Docker.onDockerEvent (/home/node/app/watchers/providers/docker/Docker.js:328:34)
    at IncomingMessage.<anonymous> (/home/node/app/watchers/providers/docker/Docker.js:317:51)
    at IncomingMessage.emit (node:events:517:28)
    at IncomingMessage.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at HTTPParser.parserOnBody (node:_http_common:131:24)
    at Socket.socketOnData (node:_http_client:541:22)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v18.20.4
```

**Comment by samcro1967** [comment]
I am seeing the same issue.  Seems to work for a day or two and then dies.  Removing the container and wud.json seems to fix it for another day or two.

**Comment by freakshock88** [comment]
I'm seeing the same issue, but I'm also using a [docker socket proxy](https://github.com/Tecnativa/docker-socket-proxy). Perhaps this proxy returns invalid JSON sometimes? Are you guys using docker socket proxies as well?

**Comment by mcarlosro** [comment]
I'm not using docker socket proxy. My configuration: WUD running on synology NAS and also access to another docker daemon using tcp on a raspberry.

**Comment by Mateuscppoi** [comment]
Had the same error here with the keycloak image (@freakshock88 i'm also using docker socket proxy), seeing the trace it looks like there is a issue with the socket connection for watching events, setting the watchevents variable to false solved the error for now.

``` yaml
whatsupdocker:
    image: ghcr.io/getwud/wud:7.1.1
    container_name: wud
    environment:
     - WUD_WATCHER_{watcher_name}_WATCHEVENTS=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - wud_data:/store
    ports:
      - 3000:3000
```

Error log:

```
{"status":"start","id":"18c3c17e212c863b57c23c8f6e1e7078126fe30777fadf205283f10eef836734","from":"quay.io/keycloak/keycloak:26.0","Type":"container","Action":"start","Actor":{"ID":"18c3c17e212c863b57c23c8f6e1e7078126fe30777fadf205283f10eef836734","Attributes":{"architecture":"x86_64","build-date":"2024-08-27T19:24:54","com.docker.compose.config-hash":"f979ab8600db5842553dd0a501292437ce141ee1465f36d6705f6073abc941b8","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:29f6f3ccacfc7d5959df4c2641bc8d311abbea32c07ce35fa0d289680e6d318b","com.docker.compose.oneoff":"False","com.docker.compose.project":"keycloak","com.docker.compose.project.config_files":"/data/compose/94/docker-compose.yml","com.docker.compose.project.environment_file":"/data/compose/94/stack.env","com.docker.compose.project.working_dir":"/data/compose/94","com.docker.compose.replace":"1b8d7590fe3baf216912a819180c4c7e5c0c24402af1510932b872be42faccf6","com.docker.compose.service":"keycloak","com.docker.compose.version":"2.29.2","com.redhat.build-host":"","com.redhat.component":"","com.redhat.license_terms":"","description":"Keycloak Server Image","distribution-scope":"public","image":"quay.io/keycloak/keycloak:26.0","io.buildah.version":"1.29.0","io.k8s.description":"Keycloak Server Image","io.k8s.display-name":"Keycloak Server","io.openshift.expose-services":"","io.openshift.tags":"keycloak security 
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Docker.onDockerEvent (/home/node/app/watchers/providers/docker/Docker.js:331:34)
    at IncomingMessage.<anonymous> (/home/node/app/watchers/providers/docker/Docker.js:320:51)
    at IncomingMessage.emit (node:events:517:28)
    at IncomingMessage.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at HTTPParser.parserOnBody (node:_http_common:131:24)
    at Socket.socketOnData (node:_http_client:541:22)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by baffian** [comment]
Ive got the same Problem with the Beszel-agent Image in V0.12.6 and only with this Application. Im using Docker Proxy to connect to several host, but the problem is with each host also on the main host itself without docker proxy

` 
  <anonymous_script>:1
    
    {"status":"create","id":"c4c2c7281cbe5a10c9bfc83665ca1d97ef45b84aa21a16ea240bb7b70415db1c","from":"henrygd/beszel-agent:latest","Type":"container","Action":"create","Actor":{"ID":"c4c2c7281cbe5a10c9bfc83665ca1d97ef45b84aa21a16ea240bb7b70415db1c","Attributes":{"com.docker.compose.config-hash":"488aeb0c6f425fe0fefaf88aa0497c0663fb11108e829e0b15d1cc59065d6e9c","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:3406875c441f95e82c22977076c04fc5b073db1eebc38732d2e26ba9b372da10","com.docker.compose.oneoff":"False","com.docker.compose.project":"beszel","com.docker.compose.project.config_files":"/data/compose/181/beszel-agent.yml","com.docker.compose.project.working_dir":"/data/compose/181","com.docker.compose.replace":"d5d38555cffa012c0f16f9e26ca18c1ef77e980b3a4ac5fad1af9cb12ac543eb","com.docker.compose.service":"beszel-agent","com.docker.compose.version":"","image":"henrygd/beszel-agent:latest","name":"d5d38555cffa_beszel-agent","org.opencontainers.image.created":"2025-08-29T21:30:46.065Z","org.opencontainers.image.description":"Lightweight server monitoring hub with historical data, docker stats, and alerts.","org.opencontainers.image.licenses":"MIT","org.opencontainers.image.revision":"0c32be3bea3fd439517cd5f4f655d36831abe998","org.opencontainers.image.source":"https://github.com/henrygd/beszel","org.opencontainers.image.title":"beszel","org.opencontainers.image.ur
    
    SyntaxError: Unterminated string in JSON at position 1443 (line 1 column 1444)
    
    at JSON.parse (<anonymous>)

    at Docker.onDockerEvent (/home/node/app/watchers/providers/docker/Docker.js:383:34)

    at IncomingMessage.<anonymous> (/home/node/app/watchers/providers/docker/Docker.js:372:51)

    at IncomingMessage.emit (node:events:507:28)

    at IncomingMessage.emit (node:domain:489:12)

    at addChunk (node:internal/streams/readable:559:12)

    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)

    at Readable.push (node:internal/streams/readable:390:5)

    at HTTPParser.parserOnBody (node:_http_common:129:24)

    at Socket.socketOnData (node:_http_client:558:22)

    at Socket.emit (node:events:507:28)

    at Socket.emit (node:domain:489:12)

    at addChunk (node:internal/streams/readable:559:12)

    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)

    at Readable.push (node:internal/streams/readable:390:5)

    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)

Node.js v23.11.1
`
