### ISSUE TITLE
Error when processing internal error code:500

### ISSUE THREAD

**Issue by Pampersfr** [getwud/wud#491]
### Hi, i have Wud installed as docker compose on debian, i have one docker "traefik" with internal error when wud processing :

`20:00:09.729  WARN whats-up-docker/watcher.docker.traefik: Error when processing (500 - {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":"s3aws: InternalError: We encountered an internal error. Please try again.\n\tstatus code: 500, request id: SJZ3NPYGHA00GF6N, host id: ziXd7JaGMdugHKkhvlIRX0OIQZEzE9ufXTYZ9yW9LvIn7aD7O7J4YW7FYhNe2vODjhPj/uK2Xt8="}]}) (container=traefik_traefik)
20:00:09.730 DEBUG whats-up-docker/watcher.docker.traefik: 500 - {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":"s3aws: InternalError: We encountered an internal error. Please try again.\n\tstatus code: 500, request id: SJZ3NPYGHA00GF6N, host id: ziXd7JaGMdugHKkhvlIRX0OIQZEzE9ufXTYZ9yW9LvIn7aD7O7J4YW7FYhNe2vODjhPj/uK2Xt8="}]} (container=traefik_traefik)
    StatusCodeError: 500 - {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":"s3aws: InternalError: We encountered an internal error. Please try again.\n\tstatus code: 500, request id: SJZ3NPYGHA00GF6N, host id: ziXd7JaGMdugHKkhvlIRX0OIQZEzE9ufXTYZ9yW9LvIn7aD7O7J4YW7FYhNe2vODjhPj/uK2Xt8="}]}
        at plumbing.callback (/home/node/app/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:104:33)
        at new StatusCodeError (/home/node/app/node_modules/request-promise-native/node_modules/request-promise-core/lib/errors.js:32:15)
        at Request.RP$callback [as _callback] (/home/node/app/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:46:31)
        at self.callback (/home/node/app/node_modules/request/request.js:185:22)
        at Request.emit (node:events:517:28)
        at Request.emit (node:domain:489:12)
        at Request.<anonymous> (/home/node/app/node_modules/request/request.js:1154:10)
        at IncomingMessage.<anonymous> (/home/node/app/node_modules/request/request.js:1076:12)
        at IncomingMessage.emit (node:events:529:35)
        at Object.onceWrapper (node:events:631:28)
        at IncomingMessage.emit (node:domain:489:12)
        at endReadableNT (node:internal/streams/readable:1400:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

### in traefik docker compose : 

`    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/traefik/traefik/releases/tag/v$${major}.$${minor}.$${patch}'
      - 'wud.display.name=Traefik'
      - 'wud.display.icon=mdi-arrow-decision'
`
### in home assistant : 
...
`image_created: "2024-10-28T15:43:40.000Z"
update_available: false
update_kind_kind: unknown
link: https://github.com/traefik/traefik/releases/tag/v3.2.0
error_message: >-
  500 - {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":"s3aws:
  InternalError: We encountered an internal error. Please try again.\n\tstatus
  code: 500, request id: SJZ3NPYGHA00GF6N, host id:
  ziXd7JaGMdugHKkhvlIRX0OIQZEzE9ufXTYZ9yW9LvIn7aD7O7J4YW7FYhNe2vODjhPj/uK2Xt8="}]}
entity_picture: https://github.com/fmartinou/whats-up-docker/raw/master/docs/wud_logo.png
icon: mdi:arrow-decision
friendly_name: Traefik
supported_features: 0`
...

Thanks for your helps
regards

**Comment by fmartinou** [comment]
Hi,

The error is refering to AWS S3 🤔 
`s3aws: InternalError: We encountered an internal error. Please try again.`

That's weird...
Are you directly pulling your images from the Docker Hub? No intermediate proxy cache by any chance?

Maybe is Docker Hub storing the images on S3?

Are you still experiencing this issue?

**Comment by WhiteSockedDancer** [comment]
We also get this error on different containers/images but they also disappear again:

500 - {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":"s3aws: InternalError: We encountered an internal error. Please try again.\n\tstatus code: 500, request id: Q1BEGZY36SPGXCE2, host id: eBK1BO+c4nxSL6h/InmmOP4G5K4FIalPWamlaNYJLKjOaEv6wC/wi4C3yuGqpHEeEzQmgpyediU="}]} 

We also don't use any proxy cache we know of..
