### ISSUE TITLE
WUD not showing any container updates, even if they are available

### ISSUE THREAD

**Issue by Tibi-rvb** [getwud/wud#493]
Have installed WUD, in docker, on a synology, with the following conf. Running 6 docker containers qbittorent, radarr, sonarr and so on, on the same machine.

WUD is reading the containers but not reporting any update even if checking the repository, there is an update.

Am I missing something?

services:
  whatsupdocker:
    image: getwud/wud
    container_name: WUD
    security_opt:
      - no-new-privileges=true
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker/wud:/store:rw
    ports:
      - 3555:3000
    environment:
     - WUD_TRIGGER_SMTP_GMAIL_HOST=smtp.gmail.com
     - WUD_TRIGGER_SMTP_GMAIL_PORT=465
     - WUD_TRIGGER_SMTP_GMAIL_USER= 1234@google.com
     - WUD_TRIGGER_SMTP_GMAIL_PASS=token
     - WUD_TRIGGER_SMTP_GMAIL_FROM= 1234@google.com
     - WUD_TRIGGER_SMTP_GMAIL_TO= 1234@google.com
     - WUD_TRIGGER_SMTP_GMAIL_TLS_ENABLED=true
     - WUD_TRIGGER_SMTP_GMAIL_SIMPLETITLE=Container $${name} Update Available
     - WUD_TRIGGER_SMTP_GMAIL_SIMPLEBODY=Container $${name} Can Be Updated From Version $${local} To Version $${remote}
     - WUD_REGISTRY_LSCR_USERNAME=username@email.com
     - WUD_REGISTRY_LSCR_TOKEN=token
     - WUD_REGISTRY_GHCR=

**Comment by fmartinou** [comment]
Hi,

Can you share
- your logs?
- the containers you want to check and the configuration (labels) related to wud you put on them (labels)?

thanks

**Comment by Tibi-rvb** [comment]
Hi,

Thx for your feedback.
Regarding labels, i haven't change anything, just the standard install.
As for the logs, there is an error but can't understand what or where

19:00:20.235  WARN whats-up-docker/watcher.docker.local: Error when processing (Error: getaddrinfo EAI_AGAIN ghcr.io) (container=local_overseerr)
19:00:20.235 DEBUG whats-up-docker/watcher.docker.local: Error: getaddrinfo EAI_AGAIN ghcr.io (container=local_overseerr)
    RequestError: Error: getaddrinfo EAI_AGAIN ghcr.io
        at new RequestError (/home/node/app/node_modules/request-promise-native/node_modules/request-promise-core/lib/errors.js:14:15)
        at plumbing.callback (/home/node/app/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:87:29)
        at Request.RP$callback [as _callback] (/home/node/app/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:46:31)
        at self.callback (/home/node/app/node_modules/request/request.js:185:22)
        at Request.emit (node:events:517:28)
        at Request.emit (node:domain:489:12)
        at Request.onRequestError (/home/node/app/node_modules/request/request.js:877:8)
        at ClientRequest.emit (node:events:517:28)
        at ClientRequest.emit (node:domain:489:12)
        at TLSSocket.socketErrorListener (node:_http_client:501:9)
        at TLSSocket.emit (node:events:517:28)
        at TLSSocket.emit (node:domain:489:12)
        at emitErrorNT (node:internal/streams/destroy:151:8)
        at emitErrorCloseNT (node:internal/streams/destroy:116:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by fmartinou** [comment]
Hi,

You seem to have networking issues.
 EAI_AGAIN is a DNS error; that means that the container cannot resolve the ip addresses behind the fqdn `ghcr.io`.

**Comment by Tibi-rvb** [comment]
> Hi,
> 
> You seem to have networking issues. EAI_AGAIN is a DNS error; that means that the container cannot resolve the ip addresses behind the fqdn `ghcr.io`.

You are totally right ... by mistake I had some custom DNS that I forgot about it. All it;'s working perfectly now. Thank you
